services:
  - type: web
    name: burgersupreme-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: cd burgersito && pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py seed
    startCommand: cd burgersito && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        value: "est8*n1=m*04$x1^8+eqr9)pajy@=&hv3&jyo5^zhzq#md27v7"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,burgersupreme.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        value: "postgresql://postgres:Infaan%402005%40@db.ejqpnxagsyuxeariycif.supabase.co:5432/postgres?sslmode=require"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://infaanburgersupreme.vercel.app,http://localhost:5173"
      - key: PYTHON_VERSION
        value: "3.14"
